-
  branches:
    only:
    - main
  version: 9.6.1-nightly-{build}
  pull_requests:
    do_not_increment_build_number: true
  skip_tags: true
  max_jobs: 1
  image: Visual Studio 2019
  clone_depth: 1
  build_script:
  - ps: |-
      # Version number
      $BUILD_NUMBER = [int]$Env:APPVEYOR_BUILD_NUMBER
      $BUILD_SUFFIX = "nightly"

      # Branch
      $BRANCH = "$Env:APPVEYOR_REPO_BRANCH"
      $Env:DOCFX_SOURCE_BRANCH_NAME = "$BRANCH"

      # Output directory
      $Env:ARTIFACT_DIR = ".\artifacts"
      $dir = New-Item -type directory $env:ARTIFACT_DIR
      $dir = $dir.FullName

      # Verbosity
      Write-Host "Build: $BUILD_NUMBER / Branch: $BRANCH"
      Write-Host "Artifacts will be placed in: $dir"

      # Check if this is a PR
      if (-not $Env:APPVEYOR_PULL_REQUEST_NUMBER)
      {
          # Rebuild documentation
          Write-Host "Commencing complete build"
          & .\rebuild-all.ps1 -ArtifactLocation "$dir" -Configuration "Release" -VersionSuffix "$BUILD_SUFFIX" -BuildNumber $BUILD_NUMBER
          #-DocsPath ".\docs" -DocsPackageName "dcs-docs"
      }
      else
      {
          # Skip documentation
          Write-Host "Building from PR ($Env:APPVEYOR_PULL_REQUEST_NUMBER); skipping docs build"
          & .\rebuild-all.ps1 -ArtifactLocation "$dir" -Configuration "Release" -VersionSuffix "$BUILD_SUFFIX" -BuildNumber $BUILD_NUMBER
      }
  artifacts:
  - path: artifacts\*.nupkg
  - path: artifacts\dcs-docs.tar.xz
  deploy:
  - provider: NuGet
    server:
    api_key:
      secure: eml4lPttwjBZg7WdwX3tbx34ZDNssgb2zwthatNbolRY0PnaCIswbuPClf9IWrw7
    skip_symbols: true
  - provider: GitHub
    auth_token:
      secure: oMF8sv9mhVjO7pBctQOwlmfd5aHQ4hvMoVCz77bgO9+1zBQSelPHxk0bCVfXNCCp
    prerelease: true
    force_update: true
  on_success:
    - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
    - ps: ./send.ps1 success $env:WEBHOOK_URL
  on_failure:
    - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
    - ps: ./send.ps1 failure $env:WEBHOOK_URL
# Releases
-
  branches:
    only:
    - /release/
  version: 9.6.1
  pull_requests:
    do_not_increment_build_number: true
  skip_tags: true
  max_jobs: 1
  image: Visual Studio 2019
  clone_depth: 1
  build_script:
  - ps: |-
      # Version number
      $BUILD_NUMBER = [int]$Env:APPVEYOR_BUILD_NUMBER

      # Branch
      $BRANCH = "$Env:APPVEYOR_REPO_BRANCH"
      $Env:DOCFX_SOURCE_BRANCH_NAME = "$BRANCH"

      # Output directory
      $Env:ARTIFACT_DIR = ".\artifacts"
      $dir = New-Item -type directory $env:ARTIFACT_DIR
      $dir = $dir.FullName

      # Verbosity
      Write-Host "Build: $BUILD_NUMBER / Branch: $BRANCH"
      Write-Host "Artifacts will be placed in: $dir"

      # Check if this is a PR
      if (-not $Env:APPVEYOR_PULL_REQUEST_NUMBER)
      {
          # Rebuild documentation
          Write-Host "Commencing complete build"
          & .\rebuild-all.ps1 -ArtifactLocation "$dir" -Configuration "Release" -DocsPath ".\docs" -DocsPackageName "dcs-docs"
      }
      else
      {
          # Skip documentation
          Write-Host "Building from PR ($Env:APPVEYOR_PULL_REQUEST_NUMBER); skipping docs build"
          & .\rebuild-all.ps1 -ArtifactLocation "$dir" -Configuration "Release"
      }
  artifacts:
  - path: artifacts\*.nupkg
  - path: artifacts\dcs-docs.tar.xz
  deploy:
  - provider: NuGet
    server:
    api_key:
      secure: eml4lPttwjBZg7WdwX3tbx34ZDNssgb2zwthatNbolRY0PnaCIswbuPClf9IWrw7
    skip_symbols: true
  - provider: GitHub
    auth_token:
      secure: oMF8sv9mhVjO7pBctQOwlmfd5aHQ4hvMoVCz77bgO9+1zBQSelPHxk0bCVfXNCCp
    prerelease: false
    force_update: true
  on_success:
    - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
    - ps: ./send.ps1 success $env:WEBHOOK_URL
  on_failure:
    - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
    - ps: ./send.ps1 failure $env:WEBHOOK_URL
# Old stuff
  #- provider: NuGet
  #  server: https://nuget.pkg.github.com/Aiko-IT-Systems/index.json
  #  username: Lulalaby
  #  api_key:
  #    secure: 3l827zZPk7wTgnX2eZpc6bYcbOKVQnkB3xOkH43UTIHknJ0IMHrP7S6YNmgIRzkt
  #  skip_symbols: true
